# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-04 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question1',
        ),
    ]
